"""
Insights educativos categorizados por área temática.
Basados en papers existentes (Running_papers/) + nueva investigación 2021-2025.
Cada insight tiene: título, hallazgo clave con números, aplicación práctica.
"""

CATEGORIES = [
    {
        "id": "intensidad",
        "icon": "📊",
        "title": "Distribución de Intensidad",
        "subtitle": "El principio más importante del entrenamiento de resistencia",
        "color": "#E9CEA9",
        "bg": "#1A1A1A",
        "insights": [
            {
                "title": "La regla del 80/20",
                "finding": "Los atletas élite realizan ≥80% de su volumen claramente por debajo del umbral láctico (Z1), y usan la alta intensidad de forma sorprendentemente escasa. El 20% restante incluye Z2 y Z3.",
                "number": "80% Z1 · 20% Z2-Z3",
                "source": "Seiler & Tønnessen (2009)",
                "application": "En tu caso: de 5 sesiones semanales, 4 deben ser conversacionales (puedes hablar sin problema) y 1 sola debe ser dura. Si todas se sienten medianas, estás en la trampa del umbral.",
            },
            {
                "title": "La trampa de la intensidad moderada (Z2)",
                "finding": "El entrenamiento polarizado (77% Z1 / 3% Z2 / 20% Z3) mejoró el rendimiento en 10K un 5.0% vs 3.6% del entrenamiento en umbral (46% Z1 / 35% Z2 / 19% Z3) en corredores recreativos durante 10 semanas.",
                "number": "+1.4% de mejora extra con el modelo polarizado",
                "source": "Muñoz et al. (2014) — IJSPP",
                "application": "Evita el 'gris': correr a ritmo 'cómodo pero sostenido' la mayoría del tiempo es la estrategia subóptima más común. Lo fácil debe ser muy fácil (FC <125 bpm). Lo difícil debe ser verdaderamente difícil.",
            },
            {
                "title": "El entrenamiento polarizado mejora el VO2max",
                "finding": "Meta-análisis de 17 estudios (n=437): el entrenamiento polarizado es superior para mejorar el VO2peak (SMD=0.24, p=0.040), especialmente en intervenciones <12 semanas y atletas altamente entrenados.",
                "number": "SMD = 0.24 → ventaja real y significativa",
                "source": "Silva Oliveira et al. (2024) — Sports Medicine",
                "application": "El VO2max es tu motor. Mejorarlo con el modelo polarizado en 8-12 semanas es más efectivo que cualquier otro modelo. Esto es especialmente relevante en tu plan de medio maratón.",
            },
            {
                "title": "Los mejores entrenadores del mundo usan 2-3 sesiones clave",
                "finding": "12 entrenadores noruegos con >380 medallas internacionales entre todos coinciden: semana centrada en 2-3 sesiones clave (intensas), el resto volumen Z1. El 80-90% del tiempo total en baja intensidad.",
                "number": "2-3 sesiones duras · 80-90% volumen en Z1",
                "source": "Sandbakk et al. (2025) — Sports Medicine Open",
                "application": "Tu plan Runna ya está diseñado así. El ciclismo que se añade va en los días de descanso entre sesiones clave, siempre en Z1 para no comprometer la calidad de las sesiones duras.",
            },
        ],
    },
    {
        "id": "altitud",
        "icon": "⛰️",
        "title": "Ventaja de Bogotá",
        "subtitle": "Por qué vivir a 2.600 m te hace mejor corredor",
        "color": "#10B981",
        "bg": "#1A1A1A",
        "insights": [
            {
                "title": "Vives en el ambiente óptimo de altitud",
                "finding": "La altitud mínima efectiva para estimular la producción de EPO y aumentar la masa de hemoglobina es ~2000-2200 m. Bogotá está a 2600 m — dentro del rango óptimo. Después de 4 semanas de entrenamiento en altitud real, el VO2max aumenta 4-8%, significativamente más que la altitud simulada (2-4%).",
                "number": "+4 a +8% VO2max tras 4 semanas en altitud real",
                "source": "Life — MDPI (2025)",
                "application": "Llevas años acumulando este beneficio sin saberlo. Tu masa de hemoglobina total es crónicamente más alta que un corredor de nivel del mar equivalente. Cuando viajes a competir a nivel del mar, tu ventaja es máxima entre los días 2 y 14 después de bajar.",
            },
            {
                "title": "HIIT en altitud mejora más el VO2max",
                "finding": "HIIT bajo hipoxia natural mejoró el VO2max entre 4.4-13% vs 1-8.3% bajo normoxia en corredores de fondo. El efecto no dependió del tipo de hipoxia, estado de entrenamiento ni sexo (todos los p > 0.30).",
                "number": "Hipoxia natural: hasta +13% VO2max vs +8.3% a nivel del mar",
                "source": "Fentaw et al. (2025) — Physiological Reports",
                "application": "Tus intervalos (Hill Repeats, 1km Repeats de Runna) son más valiosos de lo que crees porque los haces a 2600 m. Regúlalos por FC o RPE, nunca por pace de nivel del mar — sentirás que vas ~10-12% más lento para el mismo esfuerzo.",
            },
            {
                "title": "La densidad mitocondrial aumenta 20-30%",
                "finding": "Tras 4 semanas en altitud real, la densidad mitocondrial muscular aumenta 20-30% y la densidad capilar mejora — facilitando la difusión de oxígeno. Estos beneficios persisten 2-4 semanas al regresar al nivel del mar.",
                "number": "+20 a +30% densidad mitocondrial",
                "source": "Life — MDPI (2025)",
                "application": "Cada semana de entrenamiento constante en Bogotá es una inversión mitocondrial. La base aeróbica que construyes aquí es más densa y eficiente que la de un corredor de nivel del mar con el mismo volumen.",
            },
            {
                "title": "El sueño en altitud es de menor calidad",
                "finding": "La hipoxia a 2600 m induce respiración periódica durante el sueño, reduciendo la eficiencia del sueño y los ciclos REM. Esto hace que la higiene del sueño sea MÁS importante en Bogotá, no menos.",
                "number": "8-9 horas en cama recomendadas (vs 7-8 a nivel del mar)",
                "source": "Sports Medicine Open (2023)",
                "application": "Apunta a 8-9 horas en cama para compensar la menor eficiencia. Eleva ligeramente la cabecera de la cama. Evita alcohol (empeora la respiración periódica nocturna). Tu HRV matutino bajo puede reflejar mala calidad de sueño tanto como fatiga de entrenamiento.",
            },
        ],
    },
    {
        "id": "fuerza",
        "icon": "💪",
        "title": "Entrenamiento de Fuerza",
        "subtitle": "Por qué el gimnasio hace al corredor más rápido",
        "color": "#CEA970",
        "bg": "#1A1A1A",
        "insights": [
            {
                "title": "La fuerza mejora la economía de carrera, no el VO2max",
                "finding": "Meta-análisis de métodos de fuerza para corredores: la fuerza de alta carga mejoró el rendimiento en time-trial y TTE, pero tuvo efectos triviales sobre VO2max, vVO2max y capacidad de sprint. El mecanismo es neuromuscular: mayor rigidez tendinosa y mejor aplicación de fuerza por zancada.",
                "number": "Efecto en RE: g = -0.32 (pequeño pero significativo)",
                "source": "Llanos-Lagos et al. (2024) — Sports Medicine",
                "application": "No vayas al gym para tener más 'motor'. Ve para usar tu motor existente de forma más eficiente. Cada zancada consume menos energía. En un medio maratón esto se traduce en segundos por kilómetro ahorrados sin esfuerzo adicional.",
            },
            {
                "title": "Combinación de métodos = mayor beneficio",
                "finding": "Fuerza combinada (alta carga + pliométrica) produjo mayores ganancias de rendimiento que cualquier método solo. La fuerza de alta carga produce mayor beneficio en corredores entrenados; la pliometría es igual de efectiva en todos los niveles.",
                "number": "Combinado > alta carga sola > pliometría sola",
                "source": "Llanos-Lagos et al. (2024) — Sports Medicine",
                "application": "Martes y jueves: combina sentadillas pesadas (3-5 reps al 80% de tu máximo) con 2-3 series de pliometría (saltos, rebotes, rope skipping). 45 minutos totales es suficiente. No necesitas más.",
            },
            {
                "title": "La pliometría es ideal para corredor recreativo",
                "finding": "La pliometría mostró efectos similares a la fuerza pesada en economía de carrera, con ventajas a velocidades más lentas — exactamente las relevantes para corredores recreativos. No requiere gimnasio y reduce el riesgo de lesión.",
                "number": "Mejora RE comparable a fuerza pesada a ritmos de entrenamiento",
                "source": "Eihara et al. (2022) — Sports Medicine Open",
                "application": "Si no puedes ir al gym un día de fuerza: 3x15 saltos al cajón, 3x20 saltos con cuerda, 3x10 saltos a una pierna por lado. Hecho en 20 minutos. Es suficiente para obtener el beneficio de economía de carrera.",
            },
        ],
    },
    {
        "id": "recuperacion",
        "icon": "😴",
        "title": "Recuperación y HRV",
        "subtitle": "Cómo saber cuándo entrenar duro y cuándo descansar",
        "color": "#FFBC7D",
        "bg": "#1A1A1A",
        "insights": [
            {
                "title": "El HRV predice si puedes absorber carga",
                "finding": "El entrenamiento guiado por HRV fue superior al entrenamiento predefinido para mejorar índices de variabilidad cardíaca (SMD=+0.50). Produjo menos 'no respondedores' y menos episodios de sobreentrenamiento que el plan fijo.",
                "number": "SMD = +0.50 → ventaja pequeña-mediana significativa",
                "source": "Javaloyes et al. (2021) — IJERPH",
                "application": "Mide tu RMSSD cada mañana antes de levantarte. Si está >1 desviación estándar por debajo de tu promedio de 7 días → reemplaza la sesión dura por Z1 fácil. Esta herramienta (que ya tienes en tu Garmin) es la forma más práctica de individualizar tu plan.",
            },
            {
                "title": "El RMSSD matutino es la métrica más útil",
                "finding": "Las mediciones de HRV tomadas al despertar (antes de levantarse) son las más sensibles y reproducibles. Las mediciones más tarde en el día son menos informativas. El RMSSD, no el HRV total, es el indicador más práctico de recuperación autonómica.",
                "number": "RMSSD matutino > cualquier otra medición del día",
                "source": "Javaloyes et al. (2021) — IJERPH",
                "application": "Tu Garmin mide el HRV automáticamente mientras duermes y te da un valor matutino. Ese número en la app de Garmin Connect bajo 'Body Battery' o en la sección de HRV es tu semáforo diario. Verde = entrena fuerte. Amarillo = modera. Rojo = recupera.",
            },
            {
                "title": "Menos de 7 horas → 1.7x más riesgo de lesión",
                "finding": "Atletas que dormían menos de 7 horas/noche mostraron 1.7 veces mayor riesgo de lesión musculoesquelética. La privación aguda de sueño produjo una disminución del 10% en el rendimiento de resistencia autogestionado.",
                "number": "<7h sueño → 1.7× riesgo de lesión · -10% rendimiento",
                "source": "Sports Medicine Open (2023)",
                "application": "Antes de ajustar tu plan de entrenamiento, optimiza tu sueño. Es la intervención con mejor ratio esfuerzo/beneficio en todo el deporte. Una semana de 8+ horas de sueño puede mejorar tu rendimiento tanto como una semana de entrenamiento extra.",
            },
            {
                "title": "Las siestas de 30-60 min aceleran la recuperación",
                "finding": "Siestas de 30-60 minutos tomadas 1-3 veces por semana mejoraron consistentemente los marcadores de recuperación, especialmente cuando se programaron ≥60 minutos antes de cualquier sesión dura o competencia.",
                "number": "30-60 min · al menos 60 min antes de entrenar",
                "source": "Sports Medicine Open (2023)",
                "application": "Los días de entrenamiento doble (fuerza en la mañana, carrera en la tarde), una siesta de 30 minutos después del almuerzo puede ser la diferencia entre una sesión de calidad y una mediocre. No más de 30 min para no entrar en sueño profundo.",
            },
        ],
    },
    {
        "id": "tecnica",
        "icon": "🏃",
        "title": "Técnica de Carrera",
        "subtitle": "Cómo correr más eficiente con el mismo esfuerzo",
        "color": "#3B82F6",
        "bg": "#1A1A1A",
        "insights": [
            {
                "title": "El tipo de pisada no importa para la economía",
                "finding": "El debate talón vs. mediopié vs. punta está resuelto: el patrón de pisada no mostró diferencia significativa en economía de carrera entre grupos en revisión sistemática de 54 estudios observacionales. La economía depende de otros factores.",
                "number": "Diferencia en RE entre pisadas: no significativa",
                "source": "Van Hooren et al. (2024) — Sports Medicine",
                "application": "No cambies tu pisada por moda o por consejo del vendedor de zapatillas. Si no tienes lesiones, tu pisada actual es probablemente la más eficiente para tu biomecánica. El cambio de pisada sin lesión es una fuente de lesión, no de mejora.",
            },
            {
                "title": "Reducir el rebote vertical es la clave",
                "finding": "Las variables más consistentemente asociadas con mejor economía de carrera: menor oscilación vertical, mayor rigidez de pierna, menor tiempo de contacto con el suelo y mayor velocidad en umbral anaeróbico.",
                "number": "Menor oscilación vertical = menor costo energético por km",
                "source": "Van Hooren et al. (2024) — Sports Medicine",
                "application": "Grábate corriendo de frente con el celular. Si 'botas' visiblemente hacia arriba, estás desperdiciando energía. Piensa en 'correr hacia adelante, no hacia arriba'. Cadencia más alta automáticamente reduce el rebote vertical.",
            },
            {
                "title": "Aumentar cadencia 5-10% reduce las lesiones",
                "finding": "Un aumento de cadencia del 10% redujo las fuerzas de reacción verticales del suelo y las tasas de carga — sin costo metabólico adicional en ninguna condición probada. Combinado con zapatillas de menor drop, el efecto fue mayor.",
                "number": "+10% cadencia → reducción significativa de fuerzas de impacto",
                "source": "JFMK — MDPI (2025)",
                "application": "Si corres a <165 pasos/minuto, experimenta subir a ~170-175 spm. La mayoría de relojes Garmin pueden mostrarte tu cadencia en tiempo real. Más pasos cortos = menos impacto en cada zancada = menos riesgo de lesión acumulada.",
            },
            {
                "title": "Tiempo en umbral anaeróbico predice el rendimiento",
                "finding": "La velocidad o potencia en el segundo umbral ventilatorio/láctico (VT2/LT2) fue el predictor de rendimiento más consistente en resistencia. Más que el VO2max puro, la capacidad de mantener alta velocidad cerca del umbral define tu tiempo de carrera.",
                "number": "Velocidad en LT2 > VO2max como predictor de tiempo de carrera",
                "source": "Van Hooren et al. (2024) — Sports Medicine",
                "application": "Tus sesiones de tempo (Runna) que trabajan cerca del umbral son las más específicas para mejorar tu tiempo de medio maratón. No las omitas. Son el puente entre tu base aeróbica (Z1) y tu capacidad de carrera (VO2max).",
            },
        ],
    },
    {
        "id": "nutricion",
        "icon": "🥗",
        "title": "Nutrición para Corredores",
        "subtitle": "Cuándo comer carbohidratos y cuándo no",
        "color": "#10B981",
        "bg": "#1A1A1A",
        "insights": [
            {
                "title": "Entrena bajo, compite alto",
                "finding": "La periodización de carbohidratos (entrenar estratégicamente con baja disponibilidad de CHO) no mejoró el rendimiento final vs. alta disponibilidad de CHO constante (SMD=0.17, p=0.29), pero sí mejoró la flexibilidad metabólica y la biogénesis mitocondrial.",
                "number": "Sin ventaja en rendimiento de carrera, pero sí en adaptación metabólica",
                "source": "Gejl & Nybo (2021) — JISSN",
                "application": "1-2 sesiones fáciles por semana en ayuno o con bajo glucógeno (carrera matutina sin desayuno) activan adaptaciones mitocondriales. NUNCA hagas esto en sesiones duras o largo. Para la carrera y para los intervalos: siempre con glucógeno lleno.",
            },
            {
                "title": "60-90g de carbohidratos por hora en carrera",
                "finding": "En altitud, el metabolismo de carbohidratos es el combustible preferido bajo condiciones hipóxicas — el metabolismo de grasas está relativamente deteriorado. Para esfuerzos de 90+ minutos (medio maratón), la reposición de CHO es crítica.",
                "number": "60-90 g CHO/hora durante la carrera (mix glucosa + fructosa)",
                "source": "Gejl & Nybo (2021) + evidencia de altitud",
                "application": "Para un medio maratón en Bogotá: gel cada 20-25 minutos desde el km 5. Elige geles con mezcla de maltodextrina + fructosa para absorber ambas rutas metabólicas. Si tu tiempo objetivo es >1h45min, la nutrición en carrera determina si terminas bien o 'muerto'.",
            },
            {
                "title": "El entreno bajo en CHO no sirve antes del pico",
                "finding": "La periodización de CHO se vuelve contraproducente en las 3-4 semanas finales pre-carrera cuando la especificidad de entrenamiento requiere plena disponibilidad energética para simular correctamente el esfuerzo de carrera.",
                "number": "Suspender CHO periodization 3-4 semanas antes de la competencia",
                "source": "Gejl & Nybo (2021) — JISSN",
                "application": "En las últimas 3-4 semanas antes de tu medio maratón: elimina las sesiones en ayuno, come CHO antes de todos los entrenamientos y practica exactamente lo que harás en carrera (geles, bebidas isotónicas). La fase final es de simulación, no de adaptación.",
            },
        ],
    },
]
