/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify-callback'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as GimnasioRouteImport } from './routes/gimnasio'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as CuerpoRouteImport } from './routes/cuerpo'
import { Route as AprendeRouteImport } from './routes/aprende'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'

const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify-callback',
  path: '/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const GimnasioRoute = GimnasioRouteImport.update({
  id: '/gimnasio',
  path: '/gimnasio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const CuerpoRoute = CuerpoRouteImport.update({
  id: '/cuerpo',
  path: '/cuerpo',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeRoute = AprendeRouteImport.update({
  id: '/aprende',
  path: '/aprende',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/aprende': typeof AprendeRoute
  '/cuerpo': typeof CuerpoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/gimnasio': typeof GimnasioRoute
  '/historial': typeof HistorialRoute
  '/plan': typeof PlanRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/aprende': typeof AprendeRoute
  '/cuerpo': typeof CuerpoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/gimnasio': typeof GimnasioRoute
  '/historial': typeof HistorialRoute
  '/plan': typeof PlanRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/aprende': typeof AprendeRoute
  '/cuerpo': typeof CuerpoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/gimnasio': typeof GimnasioRoute
  '/historial': typeof HistorialRoute
  '/plan': typeof PlanRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/aprende'
    | '/cuerpo'
    | '/diagnostico'
    | '/gimnasio'
    | '/historial'
    | '/plan'
    | '/spotify-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/aprende'
    | '/cuerpo'
    | '/diagnostico'
    | '/gimnasio'
    | '/historial'
    | '/plan'
    | '/spotify-callback'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/aprende'
    | '/cuerpo'
    | '/diagnostico'
    | '/gimnasio'
    | '/historial'
    | '/plan'
    | '/spotify-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AprendeRoute: typeof AprendeRoute
  CuerpoRoute: typeof CuerpoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  GimnasioRoute: typeof GimnasioRoute
  HistorialRoute: typeof HistorialRoute
  PlanRoute: typeof PlanRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotify-callback': {
      id: '/spotify-callback'
      path: '/spotify-callback'
      fullPath: '/spotify-callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gimnasio': {
      id: '/gimnasio'
      path: '/gimnasio'
      fullPath: '/gimnasio'
      preLoaderRoute: typeof GimnasioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuerpo': {
      id: '/cuerpo'
      path: '/cuerpo'
      fullPath: '/cuerpo'
      preLoaderRoute: typeof CuerpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende': {
      id: '/aprende'
      path: '/aprende'
      fullPath: '/aprende'
      preLoaderRoute: typeof AprendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AprendeRoute: AprendeRoute,
  CuerpoRoute: CuerpoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  GimnasioRoute: GimnasioRoute,
  HistorialRoute: HistorialRoute,
  PlanRoute: PlanRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
